### ISSUE TITLE
Google's CDN links should be HTTPS

### ISSUE THREAD

**Issue by coliff** [szdc/brackets-cdn-suggestions#11]
Google recommends library links should be served over HTTPS. It's fast, safe and works everywhere.

"We recommend that you load libraries from the CDN via HTTPS, even if your own website only uses HTTP. Nowadays, performance is fast and caching works just the same. The CDN's files are served with CORS and Timing-Allow headers and allowed to be cached for 1 year."
https://developers.google.com/speed/libraries/devguide

I'd like to see this plugin always use HTTPS for the links

**Comment by szdc** [comment]
Thanks, I'll add a preference for this in about 12hrs.

**Comment by coliff** [comment]
Awesome - thanks! :-)

**Comment by szdc** [comment]
Done: 962cf3a5778db3c5c4579da27251058aa9f1f534
The preference is in the edit menu :)
